dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install Pillow
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script: 
  - pytest --cov tscribe
after_success:
  - coveralls
