name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['2.7', '3.8', '3.9', '3.10']
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libmagickwand-dev
          fi
          pip install --upgrade pip
          pip install Pillow Wand
      - name: Run tests
        run: |
          python --version
          python dhash.py
