name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['2.7', '3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install Pillow Wand
      - name: Run tests
        run: |
          python --version
          test_output="$(python dhash.py)"
          if [[ -n $test_output ]]
          then
              echo $test_output
              exit 1
          else
              exit 0
          fi
